/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIReservaCRUD;

import Classes_hotel.Reserva;
import DAO_hotel.ErpDAOException;
import DAO_hotel.ReservaDAO;
import GUI.Principal;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar
 */
public class InsereReserva extends javax.swing.JFrame {

    /**
     * Creates new form Insere
     */
    public InsereReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T2 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        T7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        OK1 = new javax.swing.JButton();
        Cancela1 = new javax.swing.JButton();
        T8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Pessoa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel6.setText("ID do quarto");

        jLabel7.setText("Data");

        jLabel8.setText("ID do cliente");

        OK1.setText("Ok");
        OK1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OK1MouseClicked(evt);
            }
        });

        Cancela1.setText("Cancelar");
        Cancela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cancela1MouseClicked(evt);
            }
        });
        Cancela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancela1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Nome do cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(OK1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Cancela1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(T7)
                    .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(T8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(T8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(T6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK1)
                    .addComponent(Cancela1))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Principal.carregaComboReserva();
    }//GEN-LAST:event_formWindowClosed

    private void OK1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OK1MouseClicked
        Reserva P = new Reserva();
        Date data = null;
        int id_quarto, id_cliente;
        //char compareceu = ' ';
        String nome_cliente = null;
        //Time time;
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");

        //if ((RB0.isSelected() == false) && (RB1.isSelected() == false)) {
            //JOptionPane.showMessageDialog(rootPane, "Você precisa selecionar a presença");
        //} else {
            if (T7.getText().equals("") || T2.getText().equals("") || T6.getText().equals("") || T6.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Você precisa informar o ID do quarto e do cliente");
            } else {
                try{
                    id_quarto = Integer.parseInt(T2.getText());
                    id_cliente = Integer.parseInt(T7.getText());
                    nome_cliente = T8.getText();
                    data = dtOutput.parse(T6.getText());
                    
                }catch(Exception ex){
                    System.out.println("Erro na conversão dos IDs");
                    id_quarto = 0;
                    id_cliente = 0;
                }
                P.setId_quarto(id_quarto);
                P.setId_cliente(id_cliente);
                P.setData(data);
                P.setNome_cliente(nome_cliente);

                try {
                    ReservaDAO PDAO = new ReservaDAO();
                    PDAO.inserir(P);
                    JOptionPane.showMessageDialog(rootPane, "Inserção efetuada com sucesso!!");
                } catch (ErpDAOException ex) {
                    System.out.println("problema na inserção da reserva");
                }
                dispose();
            }
        //}
    }//GEN-LAST:event_OK1MouseClicked

    private void Cancela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancela1MouseClicked
        dispose();
    }//GEN-LAST:event_Cancela1MouseClicked

    private void Cancela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancela1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancela1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancela1;
    private javax.swing.JButton OK1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
